### PR TITLE
Remove panter rails deploy gem and remove unicorn

### PR DESCRIPTION
**Pull request by casaper**

### CODE REVIEW

**Comment by panterch** [comment]
@casaper I think you could also remove https://github.com/panterch/future_kids/blob/master/Capfile
?

**Comment by casaper** [comment]
@panterch 

> @casaper I think you could also remove https://github.com/panterch/future_kids/blob/master/Capfile
> ?

Yea, that one I've missed. Will do

**Comment by casaper** [comment]
@panterch 

> @casaper I think you could also remove Capfile

Done!

**Comment by alesrosina** [comment]
@casaper looks good to me!

**Pull request merged**
